@echo off
echo Starting Retraining Loop (Every 3 Minutes)...
:loop
echo [Retraining] Starting retraining process...
python mysite/manage.py retrain
echo [Sleeping] Waiting 3 minutes...
timeout /t 180
goto loop
