# Generated by Django 5.2.4 on 2026-01-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('predicted_label', models.CharField(max_length=10)),
                ('actual_label', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('used_for_training', models.BooleanField(default=False)),
            ],
        ),
    ]
